default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: SONU_development

test:
  <<: *default
  database: SONU_test


production:
  <<: *default
  database: SONU_production
  username: SONU
  password: <%= ENV['SONU_DATABASE_PASSWORD'] %>
